include:
  - board: seeeduino_xiao_ble
    shield: cool640db_R rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: cool640db_L rgbled_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset
 
